# Site settings
title: TurkuNLP
subtitle: 
email: 
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://turkunlp.org" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/TurkuNLP
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
